### ISSUE TITLE
MAJOR release

### ISSUE THREAD

**Issue by paulwwisl** [CJ-Systems/gitflow-cjs#10]
Would not it be logical to number newer version release starting from 2.0.0 ?

I mean people may now remember "search for [gitflow-cjs](https://github.com/CJ-Systems/gitflow-cjs)" the first time they.
But they will clearly understand "search for gitflow 2.x"

P.S. This is one of those thing that doer decides.
Whatever numbering will be, regular releases are the most important

**Comment by ChrisJStone** [comment]
> Would not it be logical to number newer version release starting from 2.0.0 ?
> 
> I mean people may now remember "search for [gitflow-cjs](https://github.com/CJ-Systems/gitflow-cjs)" the first time they. But they will clearly understand "search for gitflow 2.x"

I am in full agreement with this and had planned on doing a 2.0.0 release once I had more of the open PR's merged into my fork. Up tell now I've been a little hesitant on just cherry-picking them. However I'm starting to think that is going to be my best option moving forward. I will get a 2.x release pushed out.
